// eslint-disable-next-line no-unused-expressions
export const data = [
  {
    quiz: 'home life',
    questions: [
      'What Was The First Home Cooked Meal You Both Had?',
      'Who Takes Longer To Get Dressed, Use Your First Name Or Your Spouses First Name?',
      'Who Takes Longer Showers, Use Your First Name Or Your Spouses First Name?',
      'Who Is Better At Keeping Your Homestead Clean, Use Your First Name Or Your Spouses First Name?',
      'Who cooks better You Or Your Spouse, Use Your First Name Or Your Spouses First Name?',
      'Most Likely To Lock Himself/Herself Out Of The House, Use Your First Name Or Your Spouses First Name?',
      'Most Likely To Lose Their House Keys, Use Your First Name Or Your Spouses First Name?',
      'Most Likely To Stay In Bed All Day, Use Your First Name Or Your Spouses First Name?',
      'Most Likely To Not Want To Clean, Use Your First Name Or Your Spouses First Name?',
      'Most Likely To Go Shopping For Groceries, Use Your First Name Or Your Spouses First Name?',
      'Question Completed!',
    ],
  },
  {
    quiz: 'Your Relationship History',
    questions: [
      'Where Did You First Kiss?',
      'Where Was Your First Date?',
      'What Was The First Movie You Both Watched TOgether?',
      'First Beach You both First Visted?',
      'On Your First Date How Did You Both Dress, Casual/Semi-Casual/Formal?',
      'Who Gave A Gift To Whom First,',
      'What was the first trip you two took together, Use Your First Name Or Your Spouses First Name?',
      "Who said 'I love you' first?",
      'When did you start dating?',
      "Who Asked Who On a Date First?",
      'Question Completed!',
    ],
  },
  {
    quiz: 'How Well Do You Really Know Them?',
    questions: [
      'If They Could Spend $500 on Anything, How Would They Spend It?',
      'If They Could Pick Up and Go Anywhere In The World Right Now, Where Would They Go?',
      'What Adjective Would Your Spouse Use to Describe Themselves?',
      "What is Your Spouse's Favorite Junk Food?",
      'How Would Your Spouse Spend The Ideal Vacation?',
      'What Is A Sure-fire Way To Get on Their Nerves?',
      "What is Something They do Constantly That They Aren't Aware Of?",
      'What Would Be Your Spouse’s Ideal Date?',
      'Which would they choose: the power of flight, or the power of time-travel?',
      'If they could spend $500 on anything, how would they spend it?',
      'Question Completed!',
    ],
  },
];
