// eslint-disable-next-line no-unused-expressions
export const data = [
  {
    quiz: 'home life',
    questions: [
      'What Was The First Home Cooked Meal You Both Had?',
      'Who Takes Longer To Get Dressed, Use Your First Name Or Your Spouses First Name?',
      'Who Takes Longer Showers, Use Your First Name Or Your Spouses First Name?',
      'Who Is Better At Keeping Your Homestead Clean, Use Your First Name Or Your Spouses First Name?',
      'Who cooks better You Or Your Spouse, Use Your First Name Or Your Spouses First Name?',
      'Most Likely To Lock Himself/Herself Out Of The House, Use Your First Name Or Your Spouses First Name?',
      'Most Likely To Lose Their House Keys, Use Your First Name Or Your Spouses First Name?',
      'Most Likely To Stay In Bed All Day, Use Your First Name Or Your Spouses First Name?',
      '',
      '',
      'Question Completed!',
    ],
  },
  {
    quiz: 'Your Relationship History',
    questions: [
      'When And Where Did You First Kiss?',
      'What Was Your First Impression Of Your Spouse?',
      'How would you describe your spouse on your first date?',
      'When did you know your spouse was the one?',
      'What was your spouse wearing the first time you met them?',
      'What Was The First Gift Your Spouse Got You?',
      'What was the first trip you two took together?',
      "Who said 'I love you' first?",
      'When did you start dating?',
      "Who said 'I love you' first?",
      'Question Completed!',
    ],
  },
  {
    quiz: 'How Well Do You Really Know Them?',
    questions: [
      'If They Could Spend $500 on Anything, How Would They Spend It?',
      'If They Could Pick Up and Go Anywhere In The World Right Now, Where Would They Go?',
      'What Adjective Would Your Spouse Use to Describe Themselves?',
      "What is Your Spouse's Favorite Junk Food?",
      'How Would Your Spouse Spend The Ideal Vacation?',
      'What Is A Sure-fire Way To Get on Their Nerves?',
      "What is Something They do Constantly That They Aren't Aware Of?",
      'What Would Be Your Spouse’s Ideal Date?',
      'Which would they choose: the power of flight, or the power of time-travel?',
      'If they could spend $500 on anything, how would they spend it?',
      'Question Completed!',
    ],
  },
];
